import breakfast from "../../public/breakfast.jpg";
import water from "../../public/water.jpg";
import vegetables from "../../public/sayurbuah.jpg";
import food from "../../public/aneka.jpg";
import label from "../../public/label.png";
import lemak from "../../public/lemak.jpg";
import pokok from "../../public/pokok.png";
import protein from "../../public/protein.jpg";
import sport from "../../public/sport.png";
import washHand from "../../public/wash.jpg";

export const tips = [
  {
    id: 1,
    text: "Syukuri dan nikmati aneka ragam makanan",
    imageSrc: food,
    colorClass: "bg-yellow-400",
    desc: "Pemenuhan kebutuhan gizi dapat dengan mengonsumsi jenis pangan yang bervariasi agar dapat terciptanya kualitas gizi yang baik.",
    desc2: "Kualitas gizi dan kelengkapan zat gizi dipengaruhi oleh keragaman jenis pangan yang dikonsumsi. Semakin beragam jenis pangan yang dikonsumsi semakin mudah untuk memenuhi kebutuhan gizi. Bahkan semakin beragam pangan yang dikonsumsi semakin mudah tubuh memperoleh berbagai zat lainnya yang bermanfaat bagi kesehatan. Oleh karena itu, konsumsi aneka ragam pangan merupakan salah satu anjuran penting dalam mewujudkan gizi seimbang.",
    desc3: "Cara menerapkan pesan ini adalah dengan mengonsumsi lima kelompok pangan setiap hari atau setiap kali makan. Kelima kelompok pangan tersebut adalah makanan pokok, lauk-pauk, sayuran, buah-buahan dan minuman. Mengonsumsi lebih dari satu jenis untuk setiap kelompok makanan (makanan pokok, lauk pauk, sayuran dan buah-buahan) setiap kali makan akan lebih baik.",
    desc4: "Setiap orang diharapkan selalu bersyukur dan menikmati makanan yang dikonsumsinya. Bersyukur dapat diwujudkan berupa berdoa sebelum makan. Nikmatnya makan ditentukan oleh kesesuaian kombinasi anekaragam dan bumbu, cara pengolahan, penyajian makanan dan suasana makan. Cara makan yang baik adalah makan yang tidak tergesa-gesa. Dengan bersyukur dan menikmati makan aneka ragam makanan akan mendukung terwujudnya cara makan yang baik, tidak tergesa-gesa. Dengan demikian makanan dapat dikunyah, dicerna dan diserap oleh tubuh lebih baik.",
  },
  {
    id: 2,
    text: "Banyak makan sayuran dan cukup buah-buahan",
    imageSrc: vegetables,
    colorClass: "bg-green-400",
    desc1: "Sayuran dan buah-buahan merupakan sumber berbagai vitamin, mineral, dan serat pangan. Vitamin dan mineral dalam sayur dan buah berperan sebagai antioksidan.",
    desc2: "Sayuran kaya serat, sedangkan buah kaya karbohidrat seperti fruktosa dan glukosa. Sayur tertentu seperti wortel dan kentang sayur juga mengandung karbohidrat. Buah tertentu seperti alpukat dan buah merah mengandung lemak tidak jenuh. Konsumsi sayur dan buah penting untuk gizi seimbang.",
    desc3: "Konsumsi sayur dan buah cukup membantu menjaga tekanan darah, kadar gula, dan kolesterol darah. Konsumsi sayur dan buah cukup juga menurunkan risiko sembelit, kegemukan, dan penyakit tidak menular kronik. Konsumsi sayur dan buah cukup merupakan salah satu indikator sederhana gizi seimbang.",
    desc4: "Semakin matang buah, semakin tinggi kandungan fruktosa dan glukosanya, dan semakin manis rasanya. Jus buah bergula mengandung 150-300 kalori, separohnya dari gula tambahan. Konsumsi buah terlalu matang dan jus bergula perlu dibatasi untuk mengendalikan kadar gula darah.",
    desc5: "WHO menganjurkan konsumsi sayur dan buah 400 g per orang per hari, terdiri dari 250 g sayur (2 ½ porsi) dan 150 g buah (3 pisang ambon, 1 ½ potong pepaya, atau 3 jeruk).",
    desc6: "Bagi orang Indonesia, anjuran konsumsi sayur dan buah adalah 300-400 g per orang per hari untuk anak balita dan anak usia sekolah, dan 400-600 g per orang per hari untuk remaja dan orang dewasa. Sekitar dua pertiga dari jumlah tersebut adalah porsi sayur. (PMK No. 41 Tahun 2014)"
  },
  {
    id: 3,
    text: "Biasakan mengonsumsi lauk pauk berprotein tinggi",
    imageSrc: protein,
    colorClass: "bg-red-600",
    desc1: "Lauk pauk terbagi menjadi dua sumber protein, yaitu hewani dan nabati. Protein hewani meliputi daging ruminansia (sapi, kambing, rusa), daging unggas (ayam, bebek), ikan dan seafood, telur, serta susu dan hasil olahannya. Sementara protein nabati berasal dari kacang-kacangan dan hasil olahannya seperti kedelai, tahu, tempe, kacang hijau, dan lain-lain.",
    desc2: "Meskipun sama-sama menyediakan protein, kedua kelompok pangan ini memiliki kelebihan dan kekurangan. Protein hewani unggul dalam kandungan asam amino yang lengkap dan mutu zat gizi seperti protein, vitamin, dan mineral. Protein hewani juga lebih mudah diserap tubuh. Namun, protein hewani  biasanya tinggi kolesterol (kecuali ikan) dan lemak, terutama lemak jenuh yang berasal dari daging dan unggas.",
    desc3: "Protein nabati, di sisi lain, memiliki keunggulan kandungan lemak tidak jenuh yang lebih banyak.  Selain itu, protein nabati mengandung isoflavon, sejenis fitokimia yang berfungsi mirip hormon estrogen, antioksidan, dan anti-kolesterol. Konsumsi kedelai dan tempe bahkan terbukti dapat menurunkan kolesterol dan meningkatkan sensitifitas insulin, sehingga dapat mengendalikan kadar kolesterol dan gula darah. Namun, kualitas protein dan mineral yang dikandung protein nabati lebih rendah dibanding protein hewani.",
    desc4: "Untuk mewujudkan Gizi Seimbang, kedua kelompok pangan ini perlu dikonsumsi bersama setiap hari. Kebutuhan protein hewani dianjurkan 2-4 porsi per hari, setara dengan 70-140 gram daging sapi, 80-160 gram daging ayam/ikan. Sementara kebutuhan protein nabati 2-4 porsi per hari, setara dengan 100-200 gram tempe atau 200-400 gram tahu. Porsi yang dianjurkan ini tetap bergantung pada kelompok umur dan kondisi fisiologis.",
    desc5: "Susu sebagai bagian dari protein hewani dianjurkan terutama bagi ibu hamil, menyusui, dan anak-anak setelah usia satu tahun. Bagi mereka yang mengalami diare atau intoleransi laktosa, konsumsi susu hewani tidak dianjurkan. Alternatif yang bisa dipilih adalah telur, susu kedelai, atau ikan.",
  },
  {
    id: 4,
    text: "Biasakan mengonsumsi aneka ragam makanan pokok",
    imageSrc: pokok,
    colorClass: "bg-yellow-700",
    desc1: "Makanan pokok memiliki kandungan karbohidrat. Contohnya, yaitu beras, kentang, singkong, ubi, talas, garut, sorgum, jewawut, sagu dan produk olahannya.",
    desc2: "Disamping mengandung karbohidrat, dalam makanan pokok biasanya juga terkandung antara lain vitamin B1 (tiamin), B2 (riboflavin) dan beberapa mineral. Mineral dari makanan pokok ini biasanya mempunyai mutu biologis atau penyerapan oleh tubuh yang rendah.",
    desc3: "Serealia utuh seperti jagung, beras merah, beras hitam, atau biji-bijian yang tidak disosoh dalam penggilingannya mengandung serat yang tinggi. Serat ini penting untuk melancarkan buang air besar dan pengendalian kolesterol darah. Selain itu serealia tersebut juga memilki karbohidrat yang lambat diubah menjadi gula darah sehingga turut mencegah gula darah tinggi.",
    desc4: "Beberapa jenis umbi-umbian juga mengandung zat non-gizi yang bermanfaat untuk kesehatan seperti ubi jalar ungu dan ubi jalar kuning yang mengandung antosianin dan lain-lain.",
    desc5: "Cara mewujudkan pola konsumsi makanan pokok yang beragam adalah dengan mengonsumsi lebih dari satu jenis makanan pokok dalam sehari atau sekali makan. Salah satu cara mengangkat citra pangan karbohidrat lokal adalah dengan mencampur makanan karbohidrat lokal dengan terigu, seperti pengembangan produk boga yang beragam misalnya, roti atau mie campuran tepung singkong dengan tepung terigu, pembuatan roti gulung pisang, singkong goreng keju dan lain-lain.",
  },
  {
    id: 5,
    text: "Batasi konsumsi pangan asin, manis, dan berlemak",
    imageSrc: lemak,
    colorClass: "bg-red-800",
    desc1: "",
    desc2: "",
    desc3: "",
    desc4: "",
    desc5: "",
    desc6: "",
    desc7: "",
  },
  {
    id: 6,
    text: "Biasakan sarapan pagi",
    imageSrc: breakfast,
    colorClass: "bg-yellow-600",
    desc1: "",
    desc2: "",
    desc3: "",
    desc4: "",
    desc5: "",
    desc6: "",
    desc7: "",
  },
  {
    id: 7,
    text: "Biasakan meminum air putih",
    imageSrc: water,
    colorClass: "bg-blue-800",
    desc1: "",
    desc2: "",
    desc3: "",
    desc4: "",
    desc5: "",
    desc6: "",
    desc7: "",
  },
  {
    id: 8,
    text: "Biasakan membaca label pada kemasan pangan",
    imageSrc: label,
    colorClass: "bg-green-400",
    desc1: "",
    desc2: "",
    desc3: "",
    desc4: "",
    desc5: "",
    desc6: "",
    desc7: "",
  },
  {
    id: 9,
    text: "Cuci tangan dengan air bersih yang mengalir menggunakan sabun",
    imageSrc: washHand,
    colorClass: "bg-red-800",
    desc1: "",
    desc2: "",
    desc3: "",
    desc4: "",
    desc5: "",
    desc6: "",
    desc7: "",
  },
  {
    id: 10,
    text: "Melakukan aktivitas fisik yang cukup dan mempertahankan berat badan normal",
    imageSrc: sport,
    colorClass: "bg-blue-700",
    desc1: "",
    desc2: "",
    desc3: "",
    desc4: "",
    desc5: "",
    desc6: "",
    desc7: "",
  },
];
